version: 2.1

workflows:
  # test building
  test-deploy:
    jobs:
      - build-cpu

jobs:
  build-cpu:
    docker:
      - image: cimg/base:edge
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && sudo rm -rf /var/lib/apt/lists/*'
      - run: 
          name: Updating
          command: 'sudo apt-get update && 
            sudo apt-get install software-properties-common -y && 
            sudo apt-add-repository multiverse && 
            sudo apt-add-repository restricted &&
            sudo apt-get update -y'
      - run: sudo apt-get install -y \
            git cmake g++ pkg-config \
            libcfitsio-bin libcfitsio-dev \
            liblapack-dev \
            wcslib-dev wcslib-tools \
            libglib2.0-dev \
            libcasa-casa4 casacore-dev casacore-data casacore-tools \
            mpich \
            fftw3-dev libfftw3-mpi3 libfftw3-bin

